
name: subaybay-local

services:
  app:
    build: app
    restart: unless-stopped
    ports: 
      - ${APP_PORT}:3000
    env_file:
      - ./.env
    environment:
      ON_DOCKER: "true"
    depends_on:
      database:
        condition: service_started
      backend:
        condition: service_started
      docs:
        condition: service_started

  docs:
    build: docs
    restart: unless-stopped
    ports:
      - ${DOCS_PORT}:4173
    environment:
      ON_DOCKER: "true"

  backend:
    build: backend
    restart: unless-stopped
    ports: 
      - ${BACKEND_PORT}:8080
    env_file:
      - ./.env
    environment:
      ON_DOCKER: "true"
    depends_on:
      database:
        condition: service_started

  database:
    image: mongo
    restart: unless-stopped
    volumes:
       - db-data:/data/db
       - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${DATABASE_PORT}:27017
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  db-data:

