
name: subaybay

services:
  app:
    build: app
    restart: always
    ports: 
      - ${APP_PORT}:3000

  database:
    image: mongo
    restart: always
    volumes:
       - db-data:/data/db
    ports:
      - ${DATABASE_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build: backend
    restart: always
    ports: 
      - ${BACKEND_PORT}:8080


volumes:
  db-data:

