
name: subaybay

services:
  app:
    build: app
    restart: always
    ports: 
      - ${APP_PORT}:3000
    env_file:
      - ./.env.development
    depends_on:
      - backend
      - database

  database:
    image: mongo
    restart: always
    volumes:
       - db-data:/data/db
       - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${DATABASE_PORT}:27017
    env_file:
      - ./.env.development

  backend:
    build: backend
    restart: always
    ports: 
      - ${BACKEND_PORT}:8080
    env_file:
      - ./.env.development
    depends_on:
      - database


volumes:
  db-data:

