
name: subaybay

services:
  app:
    build: app
    restart: always
    ports: 
      - ${APP_PORT}:3000
    env_file:
      - ./.env.dev
    depends_on:
      - backend
      - database

  database:
    image: mongo
    restart: always
    volumes:
       - db-data:/data/db
    ports:
      - ${DATABASE_PORT}:27017
    env_file:
      - ./.env.dev

  backend:
    build: backend
    restart: always
    ports: 
      - ${BACKEND_PORT}:8080
    env_file:
      - ./.env.dev
    depends_on:
      - database


volumes:
  db-data:

