
name: subaybay

services:
  app:
    build: app
    restart: unless-stopped
    ports: 
      - ${APP_PORT}:3000
    env_file:
      - ./.env
    depends_on:
      - backend
      - database

  database:
    image: mongo
    restart: unless-stopped
    volumes:
       - db-data:/data/db
       - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${DATABASE_PORT}:27017
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  backend:
    build: backend
    restart: unless-stopped
    ports: 
      - ${BACKEND_PORT}:8080
    env_file:
      - ./.env
    depends_on:
      - database


volumes:
  db-data:

