CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER PRIMARY KEY NOT NULL,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    isAdmin BIT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS REQUESTS (
    id INTEGER PRIMARY KEY NOT NULL,
    requester VARCHAR(255),
    modeOfRequest VARCHAR(255),
    purpose VARCHAR(255),
    requirements VARCHAR(255),
    requestStatus VARCHAR(255),
    remarks VARCHAR(255),
    requestType VARCHAR(255),
    dateCompleted DATETIME, 

    FOREIGN KEY(requestType) REFERENCES REQUEST_TYPES(requestType)
);

CREATE TABLE IF NOT EXISTS REQUEST_TYPES (
    requestType VARCHAR(255) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS REQUEST_FLOW (
    requestType VARCHAR(255) NOT NULL,
    currentStage VARCHAR(255) NOT NULL, 
    nextStage VARCHAR(255) NOT NULL,

    PRIMARY KEY(requestType, currentStage, nextStage),    
    FOREIGN KEY(requestType) REFERENCES REQUEST_TYPES(requestType),
    FOREIGN KEY(currentStage) REFERENCES STAGES(stageType),
    FOREIGN KEY(nextStage) REFERENCES STAGES(stageType)
);

CREATE TABLE IF NOT EXISTS STAGES (
    stageType VARCHAR(255) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS HISTORY (
    entryId INTEGER PRIMARY KEY NOT NULL,
    requestId INTEGER NOT NULL,
    sender INTEGER NOT NULL,
    receiver INTEGER NOT NULL,
    dateSent DATETIME NOT NULL,
    stage VARCHAR(255) NOT NULL,

    FOREIGN KEY(requestId) REFERENCES REQUESTS(id),
    FOREIGN KEY(sender) REFERENCES USERS(id),
    FOREIGN KEY(receiver) REFERENCES USERS(id),
    FOREIGN KEY(stage) REFERENCES STAGES(stageType)
);
