
CREATE TABLE IF NOT EXISTS USERS (
    id INT PRIMARY KEY,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    isAdmin BIT NOT NULL DEFAULT 1
);

-- CREATE TABLE IF NOT EXISTS REQUESTS (
--     id VARCHAR(255) PRIMARY KEY NOT NULL AUTOINCREMENT,
--     code VARCHAR(255) NOT NULL,
--     requestType VARCHAR(255) FOREIGN KEY REFERENCES REQUEST_TYPES(requestType)
--     dateReceived DATETIME NOT NULL,
--     dateCompleted DATETIME, 
--     cameFrom VARCHAR(255) FOREIGN KEY REFERENCES USERS(id) ON UPDATE CASCADE
-- )

-- CREATE TABLE IF NOT EXISTS REQUEST_TYPES (
--     requestType VARCHAR(255) PRIMARY KEY NOT NULL
-- )

-- CREATE TABLE IF NOT EXISTS REQUEST_FLOW (
--     requestType PRIMARY E
--     currentStage PRIMARY 
--     nextStage 
-- )

-- CREATE TABLE IF NOT EXISTS STAGES (
--     id PRIMARY KEY NOT NULL AUTO_INCREMENT,
-- )
