
CREATE TABLE IF NOT EXISTS USERS (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS REQUESTS (
    id VARCHAR(255) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    dateReceived DATETIME NOT NULL,
    dateCompleted DATETIME, 
    cameFrom VARCHAR(255) FOREIGN KEY REFERENCES USERS(id) ON UPDATE CASCADE
)

CREATE TABLE IF NOT EXISTS REQUEST_TYPES (
    requestType VARCHAR(255) PRIMARY KEY NOT NULL
)

CREATE TABLE IF NOT EXISTS REQUEST_FLOW (
    requestType PRIMARY E
    currentStage PRIMARY 
    nextStage 
)

CREATE TABLE IF NOT EXISTS STAGES (
    id PRIMARY KEY NOT NULL AUTO_INCREMENT,
)
