name: Push Docker Images

on: 
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Build App Image
        working-directory: app
        run: | 
          docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/subaybay-app
      - name: Build Backend Image
        working-directory: backend
        run: | 
          docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/subaybay-backend
      - name: Build Docs Image
        working-directory: docs
        run: | 
          docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/subaybay-docs
      - name: Publish Images
        run: | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/subaybay-app
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/subaybay-backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/subaybay-docs
